### ISSUE TITLE
GPU implementation

### ISSUE THREAD

**Issue by nft30001** [mustafasayilan/cryptobrute#3]
i really like this as each core is working separately as worker , can we implement in GPU grids like each grid will work separately as worker ?

**Comment by mustafasayilan** [comment]
Unfortunately, I don't know enough about GPU usage.  But I will try this.  Thank you for your interest.

**Comment by nft30001** [comment]
https://www.geeksforgeeks.org/running-python-script-on-gpu/
https://thedatafrog.com/en/articles/boost-python-gpu/
https://numba.pydata.org/

can you try this please

**Comment by studyroom1** [comment]
yes GPU please , open cl or cuda , really appreciate

**Comment by mustafasayilan** [comment]
> https://www.geeksforgeeks.org/running-python-script-on-gpu/
> https://thedatafrog.com/en/articles/boost-python-gpu/
> https://numba.pydata.org/
> 
> can you try this please

I will check in next week.  I will try. 
thanks:)

**Comment by nft30001** [comment]
Thank you
