### ISSUE TITLE
Work without internet?

### ISSUE THREAD

**Issue by yashma052** [mustafasayilan/cryptobrute#5]
Hello. 

Please tell me gardash, does it work without internet?

**Comment by mustafasayilan** [comment]
yes gardash это работает без интернета
internet olmadan çalışıyor
its working without internet))

18 Mar 2022 Cum 07:24 tarihinde yashma052 ***@***.***> şunu
yazdı:

**Comment by yashma052** [comment]
EyvAllah abime 💪🏻
